server:
    port: 8185
spring:
    application:
      name: query-engine
    data:
        mongodb:
            database: mydatabase
            port: 27017
            uri: mongodb://127.0.0.1/mydatabase

#
#        neo4j:
#            password: 123456
#            uri: bolt://localhost
#            username: neo4j