server:
    port: 8185
spring:
    data:
        mongodb:
            database: mydatabase
            port: 27017
            uri: mongodb://172.23.239.75/mydatabase

#tells about the Eureka server details and its refresh time
eureka:
    client:
        service-url:
            defaultZone: http://172.23.239.75:8091/eureka/
    register-with-eureka: true
    fetch-registry: true

#
#        neo4j:
#            password: 123456
#            uri: bolt://localhost
#            username: neo4j
